openapi: 3.1.1
info:
  title: Nafath App
  version: "1.0"
servers:
  - url: mock-service.api.elm.sa/nafath
    description: mock server
paths:
  /api/v1/mfa/request:
    post:
      tags:
        - Create Request
      summary: Send MFA Request
      description: Create a new request within Nafath app for the targeted User.
      operationId: createMfaRequest
      parameters:
        - name: APP-ID
          in: header
          description: The consumer API access app id.
          required: true
          style: simple
          explode: false
          schema:
            type: string
            default: null
        - name: APP-KEY
          in: header
          description: The consumer API access app Key.
          required: true
          style: simple
          explode: false
          schema:
            type: string
            default: null
        - name: local
          in: query
          description: “ar” or “en”, default “ar” if not provided.
          required: true
          style: form
          explode: true
          schema:
            type: string
            default: null
        - name: requestId
          in: query
          description: Unique identifier to identify the callback request, created by the
            client.
          required: true
          style: form
          explode: true
          schema:
            type: string
            default: null
        - name: app_id
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            default: null
        - name: app_key
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            default: null
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: "#/components/schemas/MfaRequestModel"
        required: true
      responses:
        "200":
          description: NAFATH MFA request created
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/MfaRequestResponseDto"
  /api/v1/mfa/request/status:
    post:
      tags:
        - Get Request Status
      summary: Retrieve MFA request status.
      description: This API checks the status of the request.
      operationId: getMfaRequestStatus
      parameters:
        - name: APP-ID
          in: header
          description: The consumer API access app id.
          required: true
          style: simple
          explode: false
          schema:
            type: string
            default: null
        - name: APP-KEY
          in: header
          description: The consumer API access app Key.
          required: true
          style: simple
          explode: false
          schema:
            type: string
            default: null
        - name: app_id
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            default: null
        - name: app_key
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            default: null
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: "#/components/schemas/MfaStatusRequestModel"
        required: true
      responses:
        "200":
          description: NAFATH MFA retrieve status success
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/MfaStatusResponseDto"
  /api/v1/mfa/jwk:
    get:
      tags:
        - Retrieve JWK
      summary: Retrieve JWK
      description: Retrieve ELM JWK, to use the Key for token verification.
      operationId: getMapping
      parameters:
        - name: app_id
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            default: null
        - name: app_key
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            default: null
      responses:
        "200":
          description: OK
  /stg/api/v2/oidc/jwt:
    post:
      tags:
        - Nafath Web
      summary: Retrieve Jwt web - STG
      description: This API used to Retrieve JWT.
      parameters:
        - name: APP_ID
          in: header
          description: The consumer API access app id.
          required: true
          style: simple
          explode: false
          schema:
            type: string
            default: null
        - name: app_id
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            default: null
        - name: app_key
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            default: null
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthorizationCodeModel"
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthorizationCodeConsumeResponse"
  /stg/api/v2/oidc/jwt/valid:
    post:
      tags:
        - Nafath Web
      summary: Validate Jwt Web - STG
      description: This API used to verify JWT.
      parameters:
        - name: app_id
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            default: null
        - name: app_key
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            default: null
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JwtRequestDto"
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: boolean
                x-faker: datatype.boolean
                default: null
  /stg/api/v2/oidc/session:
    get:
      tags:
        - Nafath Web
      summary: Retrieve url for Nafath page Web - STG
      description: Create signed Nafath URI to verify end-user by redirecting the
        end-user to the retrieved URI. For each session you need to create a new
        URI. If the client needs to identify each session, the client might send
        an identity in the query parameters.
      parameters:
        - name: APP_ID
          in: header
          description: The consumer API access app id.
          required: true
          style: simple
          explode: false
          schema:
            type: string
            default: null
        - name: locale
          in: query
          description: "'ar' or 'en', default 'ar' if not provided, and used to specify
            the JWT information preferred language."
          required: true
          style: form
          explode: true
          schema:
            type: string
            default: null
        - name: requestId
          in: query
          description: Unique identifier to identify the callback request, created by the
            client.
          required: true
          style: form
          explode: true
          schema:
            type: string
            default: null
        - name: app_id
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            default: null
        - name: app_key
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            default: null
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionResponseDto"
components:
  schemas:
    MfaRequestModel:
      required:
        - nationalId
        - service
      type: object
      properties:
        nationalId:
          pattern: ^[1234569]{1}\d{9}$
          type: string
          description: Targeted User national id
          default: null
        service:
          type: string
          description: Service Type
          default: null
      default: null
    MfaRequestResponseDto:
      type: object
      properties:
        transId:
          type: string
          description: Transaction Identifier
          x-faker: lorem.words
          default: null
        random:
          type: string
          description: Random number to be display to the end-user
          x-faker: lorem.words
          default: null
      default: null
    MfaStatusRequestModel:
      required:
        - nationalId
        - random
        - transId
      type: object
      properties:
        nationalId:
          pattern: ^[123456]{1}\d{9}$
          type: string
          description: Targeted User national id
          default: null
          examples:
            - "123456789"
        transId:
          pattern: ^(?:\{{0,1}(?:[0-9a-fA-F]){8}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){12}\}{0,1})$
          type: string
          description: Transaction Id returned by Create MFA request service
          default: null
          examples:
            - bb0Fd95a-bAa2-83cE-3F36-4fFC92Fd49D0
        random:
          pattern: ^\d{2}$
          type: string
          description: Random Number returned by Create MFA request service
          default: null
      default: null
    MfaStatusResponseDto:
      type: object
      properties:
        status:
          type: string
          description: Request status.
          enum:
            - WAITING
            - EXPIRED
            - REJECTED
            - COMPLETED
          default: null
      default: null
    AuthorizationCodeModel:
      required:
        - state
      type: object
      properties:
        state:
          type: string
          description: Authorization state
          default: null
      default: null
    AuthorizationCodeConsumeResponse:
      type: object
      properties:
        state:
          type: string
          description: Authorization state
          x-faker: lorem.words
          default: null
        token:
          type: string
          description: JWT token
          x-faker: lorem.words
          default: null
      default: null
    SessionResponseDto:
      type: object
      properties:
        id:
          type: integer
          description: URI Unique identifier.
          x-faker: datatype.number
          default: null
        url:
          type: string
          description: URL session to authenticate end-user.
          x-faker: lorem.words
          default: null
        hashedState:
          type: string
          description: Unique identifier to identify the callback request, which created
            by the service provider (ELM).
          x-faker: lorem.words
          default: null
        requestId:
          type: string
          description: Unique identifier to identify the callback request, which created
            by the client.
          x-faker: lorem.words
          default: null
      default: null
    JwtRequestDto:
      required:
        - id_token
      type: object
      properties:
        id_token:
          type: string
          description: URI Unique identifier.
          default: null
      default: null
